CREATE DATABASE IF NOT EXISTS hospital_db;
USE hospital_db;


CREATE TABLE IF NOT EXISTS Patient (
Patient_ID INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(100) NOT NULL,
Age INT,
Gender VARCHAR(10),
Contact VARCHAR(15),
Address VARCHAR(100)
);


CREATE TABLE IF NOT EXISTS Doctor (
Doctor_ID INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(100),
Specialization VARCHAR(100),
Contact VARCHAR(20),
CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS Appointment (
Appointment_ID INT AUTO_INCREMENT PRIMARY KEY,
Patient_ID INT,
Doctor_ID INT,
Date DATE,
Diagnosis VARCHAR(100),
FOREIGN KEY (Patient_ID) REFERENCES Patient(Patient_ID) ON DELETE SET NULL,
FOREIGN KEY (Doctor_ID) REFERENCES Doctor(Doctor_ID) ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS Treatment (
Treatment_ID INT AUTO_INCREMENT PRIMARY KEY,
Appointment_ID INT,
Prescription TEXT,
Fees DECIMAL(10,2),
FollowUpDate DATE,
FOREIGN KEY (Appointment_ID) REFERENCES Appointment(Appointment_ID) ON DELETE CASCADE
);
